# Generated by Django 5.0.5 on 2024-05-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errortrackingformapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testform',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
