# Generated by Django 5.0.5 on 2024-05-08 06:08

import errortrackingformapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errortrackingformapp', '0002_alter_testform_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testform',
            name='data',
            field=models.JSONField(default=errortrackingformapp.models.default_grid),
        ),
        migrations.AlterField(
            model_name='testform',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
